#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using BLWTraining.Models;

namespace BLWTraining.Models	
{
	public partial class EntitiesModel : OpenAccessContext, IEntitiesModelUnitOfWork
	{
		private static string connectionStringName = @"BlwTraningConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("EntitiesModel.rlinq");
		
		public EntitiesModel()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public EntitiesModel(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public EntitiesModel(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public EntitiesModel(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public EntitiesModel(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<IdentityUser> IdentityUsers 
		{
			get
			{
				return this.GetAll<IdentityUser>();
			}
		}
		
		public IQueryable<IdentityUserClaim> IdentityUserClaims1 
		{
			get
			{
				return this.GetAll<IdentityUserClaim>();
			}
		}
		
		public IQueryable<IdentityUserLogin> IdentityUserLogins 
		{
			get
			{
				return this.GetAll<IdentityUserLogin>();
			}
		}
		
		public IQueryable<IdentityRole> IdentityRoles 
		{
			get
			{
				return this.GetAll<IdentityRole>();
			}
		}
		
		public IQueryable<Zone> Zones 
		{
			get
			{
				return this.GetAll<Zone>();
			}
		}
		
		public IQueryable<IdentityUserInRole> IdentityUserInRoles 
		{
			get
			{
				return this.GetAll<IdentityUserInRole>();
			}
		}
		
		public IQueryable<TraiiningSessions> TraiiningSessions 
		{
			get
			{
				return this.GetAll<TraiiningSessions>();
			}
		}
		
		public IQueryable<TrainingSessionFiles> TrainingSessionFiles 
		{
			get
			{
				return this.GetAll<TrainingSessionFiles>();
			}
		}
		
		public IQueryable<TraningSessionSubscriptions> TraningSessionSubscriptions 
		{
			get
			{
				return this.GetAll<TraningSessionSubscriptions>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MsSql";
			backend.ProviderName = "System.Data.SqlClient";
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of EntitiesModel.
		/// </summary>
		/// <param name="config">The BackendConfiguration of EntitiesModel.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface IEntitiesModelUnitOfWork : IUnitOfWork
	{
		IQueryable<IdentityUser> IdentityUsers
		{
			get;
		}
		IQueryable<IdentityUserClaim> IdentityUserClaims1
		{
			get;
		}
		IQueryable<IdentityUserLogin> IdentityUserLogins
		{
			get;
		}
		IQueryable<IdentityRole> IdentityRoles
		{
			get;
		}
		IQueryable<Zone> Zones
		{
			get;
		}
		IQueryable<IdentityUserInRole> IdentityUserInRoles
		{
			get;
		}
		IQueryable<TraiiningSessions> TraiiningSessions
		{
			get;
		}
		IQueryable<TrainingSessionFiles> TrainingSessionFiles
		{
			get;
		}
		IQueryable<TraningSessionSubscriptions> TraningSessionSubscriptions
		{
			get;
		}
	}
}
#pragma warning restore 1591
