#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;
using BLWTraining.Models;

namespace BLWTraining.Models	
{
	[System.Serializable()]
	public partial class IdentityUser : INotifyPropertyChanging, INotifyPropertyChanged, System.Runtime.Serialization.ISerializable
	{
		private int _id;
		[System.ComponentModel.DataAnnotations.Required()]
		[System.ComponentModel.DataAnnotations.Key()]
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				if(this._id != value)
				{
					this.OnPropertyChanging("Id");
					this._id = value;
					this.OnPropertyChanged("Id");
				}
			}
		}
		
		private string _firstName;
		[System.ComponentModel.DataAnnotations.StringLength(255)]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string FirstName
		{
			get
			{
				return this._firstName;
			}
			set
			{
				if(this._firstName != value)
				{
					this.OnPropertyChanging("FirstName");
					this._firstName = value;
					this.OnPropertyChanged("FirstName");
				}
			}
		}
		
		private string _lastName;
		[System.ComponentModel.DataAnnotations.StringLength(255)]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string LastName
		{
			get
			{
				return this._lastName;
			}
			set
			{
				if(this._lastName != value)
				{
					this.OnPropertyChanging("LastName");
					this._lastName = value;
					this.OnPropertyChanged("LastName");
				}
			}
		}
		
		private DateTime _dateOfBirth;
		[System.ComponentModel.DataAnnotations.DataType(System.ComponentModel.DataAnnotations.DataType.DateTime)]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual DateTime DateOfBirth
		{
			get
			{
				return this._dateOfBirth;
			}
			set
			{
				if(this._dateOfBirth != value)
				{
					this.OnPropertyChanging("DateOfBirth");
					this._dateOfBirth = value;
					this.OnPropertyChanged("DateOfBirth");
				}
			}
		}
		
		private int _zone;
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual int Zone
		{
			get
			{
				return this._zone;
			}
			set
			{
				if(this._zone != value)
				{
					this.OnPropertyChanging("Zone");
					this._zone = value;
					this.OnPropertyChanged("Zone");
				}
			}
		}
		
		private string _emailAddress;
		[System.ComponentModel.DataAnnotations.StringLength(255)]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string EmailAddress
		{
			get
			{
				return this._emailAddress;
			}
			set
			{
				if(this._emailAddress != value)
				{
					this.OnPropertyChanging("EmailAddress");
					this._emailAddress = value;
					this.OnPropertyChanged("EmailAddress");
				}
			}
		}
		
		private string _phoneNumber;
		[System.ComponentModel.DataAnnotations.StringLength(255)]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string PhoneNumber
		{
			get
			{
				return this._phoneNumber;
			}
			set
			{
				if(this._phoneNumber != value)
				{
					this.OnPropertyChanging("PhoneNumber");
					this._phoneNumber = value;
					this.OnPropertyChanged("PhoneNumber");
				}
			}
		}
		
		private bool _emailConfirmed;
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual bool EmailConfirmed
		{
			get
			{
				return this._emailConfirmed;
			}
			set
			{
				if(this._emailConfirmed != value)
				{
					this.OnPropertyChanging("EmailConfirmed");
					this._emailConfirmed = value;
					this.OnPropertyChanged("EmailConfirmed");
				}
			}
		}
		
		private bool _phoneNumberConfirmed;
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual bool PhoneNumberConfirmed
		{
			get
			{
				return this._phoneNumberConfirmed;
			}
			set
			{
				if(this._phoneNumberConfirmed != value)
				{
					this.OnPropertyChanging("PhoneNumberConfirmed");
					this._phoneNumberConfirmed = value;
					this.OnPropertyChanged("PhoneNumberConfirmed");
				}
			}
		}
		
		private string _passwordHash;
		[System.ComponentModel.DataAnnotations.StringLength(255)]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string PasswordHash
		{
			get
			{
				return this._passwordHash;
			}
			set
			{
				if(this._passwordHash != value)
				{
					this.OnPropertyChanging("PasswordHash");
					this._passwordHash = value;
					this.OnPropertyChanged("PasswordHash");
				}
			}
		}
		
		private string _securityStamp;
		[System.ComponentModel.DataAnnotations.StringLength(255)]
		public virtual string SecurityStamp
		{
			get
			{
				return this._securityStamp;
			}
			set
			{
				if(this._securityStamp != value)
				{
					this.OnPropertyChanging("SecurityStamp");
					this._securityStamp = value;
					this.OnPropertyChanged("SecurityStamp");
				}
			}
		}
		
		private bool _twoFactorEnabled;
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual bool TwoFactorEnabled
		{
			get
			{
				return this._twoFactorEnabled;
			}
			set
			{
				if(this._twoFactorEnabled != value)
				{
					this.OnPropertyChanging("TwoFactorEnabled");
					this._twoFactorEnabled = value;
					this.OnPropertyChanged("TwoFactorEnabled");
				}
			}
		}
		
		private DateTime? _lockOutEndDateUtc;
		[System.ComponentModel.DataAnnotations.DataType(System.ComponentModel.DataAnnotations.DataType.DateTime)]
		public virtual DateTime? LockOutEndDateUtc
		{
			get
			{
				return this._lockOutEndDateUtc;
			}
			set
			{
				if(this._lockOutEndDateUtc != value)
				{
					this.OnPropertyChanging("LockOutEndDateUtc");
					this._lockOutEndDateUtc = value;
					this.OnPropertyChanged("LockOutEndDateUtc");
				}
			}
		}
		
		private bool _lockOutEnabled;
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual bool LockOutEnabled
		{
			get
			{
				return this._lockOutEnabled;
			}
			set
			{
				if(this._lockOutEnabled != value)
				{
					this.OnPropertyChanging("LockOutEnabled");
					this._lockOutEnabled = value;
					this.OnPropertyChanged("LockOutEnabled");
				}
			}
		}
		
		private int _accessFailedCount;
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual int AccessFailedCount
		{
			get
			{
				return this._accessFailedCount;
			}
			set
			{
				if(this._accessFailedCount != value)
				{
					this.OnPropertyChanging("AccessFailedCount");
					this._accessFailedCount = value;
					this.OnPropertyChanged("AccessFailedCount");
				}
			}
		}
		
		private string _providerId;
		[System.ComponentModel.DataAnnotations.StringLength(255)]
		public virtual string ProviderId
		{
			get
			{
				return this._providerId;
			}
			set
			{
				if(this._providerId != value)
				{
					this.OnPropertyChanging("ProviderId");
					this._providerId = value;
					this.OnPropertyChanged("ProviderId");
				}
			}
		}
		
		private DateTime? _lastLogInDate;
		[System.ComponentModel.DataAnnotations.DataType(System.ComponentModel.DataAnnotations.DataType.DateTime)]
		public virtual DateTime? LastLogInDate
		{
			get
			{
				return this._lastLogInDate;
			}
			set
			{
				if(this._lastLogInDate != value)
				{
					this.OnPropertyChanging("LastLogInDate");
					this._lastLogInDate = value;
					this.OnPropertyChanged("LastLogInDate");
				}
			}
		}
		
		private string _chapter;
		[System.ComponentModel.DataAnnotations.StringLength(255)]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string Chapter
		{
			get
			{
				return this._chapter;
			}
			set
			{
				if(this._chapter != value)
				{
					this.OnPropertyChanging("Chapter");
					this._chapter = value;
					this.OnPropertyChanged("Chapter");
				}
			}
		}
		
		private string _gender;
		[System.ComponentModel.DataAnnotations.StringLength(255)]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string Gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if(this._gender != value)
				{
					this.OnPropertyChanging("Gender");
					this._gender = value;
					this.OnPropertyChanged("Gender");
				}
			}
		}
		
		private Zone _zone1;
		public virtual Zone Zone1
		{
			get
			{
				return this._zone1;
			}
			set
			{
				if(this._zone1 != value)
				{
					this.OnPropertyChanging("Zone1");
					this._zone1 = value;
					this.OnPropertyChanged("Zone1");
				}
			}
		}
		
		private IList<IdentityUserInRole> _identityUserInRoles = new List<IdentityUserInRole>();
		public virtual IList<IdentityUserInRole> IdentityUserInRoles
		{
			get
			{
				return this._identityUserInRoles;
			}
		}
		
		private IList<IdentityUserClaim> _identityUserClaims = new List<IdentityUserClaim>();
		public virtual IList<IdentityUserClaim> IdentityUserClaims
		{
			get
			{
				return this._identityUserClaims;
			}
		}
		
		private IList<IdentityUserLogin> _identityUserLogins = new List<IdentityUserLogin>();
		public virtual IList<IdentityUserLogin> IdentityUserLogins
		{
			get
			{
				return this._identityUserLogins;
			}
		}
		
		private IList<TraningSessionSubscriptions> _traningSessionSubscriptions = new List<TraningSessionSubscriptions>();
		public virtual IList<TraningSessionSubscriptions> TraningSessionSubscriptions
		{
			get
			{
				return this._traningSessionSubscriptions;
			}
		}
		
		#region INotifyPropertyChanging members
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		protected virtual void OnPropertyChanging(string propertyName)
		{
			if(this.PropertyChanging != null)
			{
				this.PropertyChanging(this, new PropertyChangingEventArgs(propertyName));
			}
		}
		
		#endregion
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
		#region ISerializable Implementation
		
		public IdentityUser()
		{
		}
		
		protected IdentityUser(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			this.Id = info.GetInt32("Id");
			this.FirstName = info.GetString("FirstName");
			this.LastName = info.GetString("LastName");
			this.DateOfBirth = (DateTime)info.GetValue("DateOfBirth", typeof(DateTime));
			this.Zone = info.GetInt32("Zone");
			this.EmailAddress = info.GetString("EmailAddress");
			this.PhoneNumber = info.GetString("PhoneNumber");
			this.EmailConfirmed = info.GetBoolean("EmailConfirmed");
			this.PhoneNumberConfirmed = info.GetBoolean("PhoneNumberConfirmed");
			this.PasswordHash = info.GetString("PasswordHash");
			this.SecurityStamp = info.GetString("SecurityStamp");
			this.TwoFactorEnabled = info.GetBoolean("TwoFactorEnabled");
			this.LockOutEndDateUtc = (DateTime?)info.GetValue("LockOutEndDateUtc", typeof(DateTime?));
			this.LockOutEnabled = info.GetBoolean("LockOutEnabled");
			this.AccessFailedCount = info.GetInt32("AccessFailedCount");
			this.ProviderId = info.GetString("ProviderId");
			this.LastLogInDate = (DateTime?)info.GetValue("LastLogInDate", typeof(DateTime?));
			this.Chapter = info.GetString("Chapter");
			this.Gender = info.GetString("Gender");
			CustomizeDeserializationProcess(info, context);
		}
		
		public virtual void GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			info.AddValue("Id", this.Id, typeof(int));
			info.AddValue("FirstName", this.FirstName, typeof(string));
			info.AddValue("LastName", this.LastName, typeof(string));
			info.AddValue("DateOfBirth", this.DateOfBirth, typeof(DateTime));
			info.AddValue("Zone", this.Zone, typeof(int));
			info.AddValue("EmailAddress", this.EmailAddress, typeof(string));
			info.AddValue("PhoneNumber", this.PhoneNumber, typeof(string));
			info.AddValue("EmailConfirmed", this.EmailConfirmed, typeof(bool));
			info.AddValue("PhoneNumberConfirmed", this.PhoneNumberConfirmed, typeof(bool));
			info.AddValue("PasswordHash", this.PasswordHash, typeof(string));
			info.AddValue("SecurityStamp", this.SecurityStamp, typeof(string));
			info.AddValue("TwoFactorEnabled", this.TwoFactorEnabled, typeof(bool));
			info.AddValue("LockOutEndDateUtc", this.LockOutEndDateUtc, typeof(DateTime?));
			info.AddValue("LockOutEnabled", this.LockOutEnabled, typeof(bool));
			info.AddValue("AccessFailedCount", this.AccessFailedCount, typeof(int));
			info.AddValue("ProviderId", this.ProviderId, typeof(string));
			info.AddValue("LastLogInDate", this.LastLogInDate, typeof(DateTime?));
			info.AddValue("Chapter", this.Chapter, typeof(string));
			info.AddValue("Gender", this.Gender, typeof(string));
			CustomizeSerializationProcess(info, context);
		}
		
		partial void CustomizeSerializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		partial void CustomizeDeserializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		#endregion
	}
}
#pragma warning restore 1591
