#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;
using BLWTraining.Models;

namespace BLWTraining.Models	
{
	[System.Serializable()]
	public partial class TrainingSessionFiles : INotifyPropertyChanging, INotifyPropertyChanged, System.Runtime.Serialization.ISerializable
	{
		private int _id;
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				if(this._id != value)
				{
					this.OnPropertyChanging("Id");
					this._id = value;
					this.OnPropertyChanged("Id");
				}
			}
		}
		
		private int _trainingSessionId;
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual int TrainingSessionId
		{
			get
			{
				return this._trainingSessionId;
			}
			set
			{
				if(this._trainingSessionId != value)
				{
					this.OnPropertyChanging("TrainingSessionId");
					this._trainingSessionId = value;
					this.OnPropertyChanged("TrainingSessionId");
				}
			}
		}
		
		private string _fileName;
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string FileName
		{
			get
			{
				return this._fileName;
			}
			set
			{
				if(this._fileName != value)
				{
					this.OnPropertyChanging("FileName");
					this._fileName = value;
					this.OnPropertyChanged("FileName");
				}
			}
		}
		
		private string _filePath;
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string FilePath
		{
			get
			{
				return this._filePath;
			}
			set
			{
				if(this._filePath != value)
				{
					this.OnPropertyChanging("FilePath");
					this._filePath = value;
					this.OnPropertyChanged("FilePath");
				}
			}
		}
		
		private string _fileType;
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string FileType
		{
			get
			{
				return this._fileType;
			}
			set
			{
				if(this._fileType != value)
				{
					this.OnPropertyChanging("FileType");
					this._fileType = value;
					this.OnPropertyChanged("FileType");
				}
			}
		}
		
		private long _fileSize;
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual long FileSize
		{
			get
			{
				return this._fileSize;
			}
			set
			{
				if(this._fileSize != value)
				{
					this.OnPropertyChanging("FileSize");
					this._fileSize = value;
					this.OnPropertyChanged("FileSize");
				}
			}
		}
		
		private TraiiningSessions _traiiningSessions;
		public virtual TraiiningSessions TraiiningSessions
		{
			get
			{
				return this._traiiningSessions;
			}
			set
			{
				if(this._traiiningSessions != value)
				{
					this.OnPropertyChanging("TraiiningSessions");
					this._traiiningSessions = value;
					this.OnPropertyChanged("TraiiningSessions");
				}
			}
		}
		
		#region INotifyPropertyChanging members
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		protected virtual void OnPropertyChanging(string propertyName)
		{
			if(this.PropertyChanging != null)
			{
				this.PropertyChanging(this, new PropertyChangingEventArgs(propertyName));
			}
		}
		
		#endregion
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
		#region ISerializable Implementation
		
		public TrainingSessionFiles()
		{
		}
		
		protected TrainingSessionFiles(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			this.Id = info.GetInt32("Id");
			this.TrainingSessionId = info.GetInt32("TrainingSessionId");
			this.FileName = info.GetString("FileName");
			this.FilePath = info.GetString("FilePath");
			this.FileType = info.GetString("FileType");
			this.FileSize = info.GetInt64("FileSize");
			CustomizeDeserializationProcess(info, context);
		}
		
		public virtual void GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			info.AddValue("Id", this.Id, typeof(int));
			info.AddValue("TrainingSessionId", this.TrainingSessionId, typeof(int));
			info.AddValue("FileName", this.FileName, typeof(string));
			info.AddValue("FilePath", this.FilePath, typeof(string));
			info.AddValue("FileType", this.FileType, typeof(string));
			info.AddValue("FileSize", this.FileSize, typeof(long));
			CustomizeSerializationProcess(info, context);
		}
		
		partial void CustomizeSerializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		partial void CustomizeDeserializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		#endregion
	}
}
#pragma warning restore 1591
