#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;
using BLWTraining.Models;

namespace BLWTraining.Models	
{
	[System.Serializable()]
	public partial class TrainingSessionLiveEvents : INotifyPropertyChanging, INotifyPropertyChanged, System.Runtime.Serialization.ISerializable
	{
		private int _id;
		[System.ComponentModel.DataAnnotations.Required()]
		[System.ComponentModel.DataAnnotations.Key()]
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				if(this._id != value)
				{
					this.OnPropertyChanging("Id");
					this._id = value;
					this.OnPropertyChanged("Id");
				}
			}
		}
		
		private DateTime _startDate;
		[System.ComponentModel.DataAnnotations.DataType(System.ComponentModel.DataAnnotations.DataType.DateTime)]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual DateTime StartDate
		{
			get
			{
				return this._startDate;
			}
			set
			{
				if(this._startDate != value)
				{
					this.OnPropertyChanging("StartDate");
					this._startDate = value;
					this.OnPropertyChanged("StartDate");
				}
			}
		}
		
		private string _fMSUrl;
		[System.ComponentModel.DataAnnotations.StringLength(255)]
		public virtual string FMSUrl
		{
			get
			{
				return this._fMSUrl;
			}
			set
			{
				if(this._fMSUrl != value)
				{
					this.OnPropertyChanging("FMSUrl");
					this._fMSUrl = value;
					this.OnPropertyChanged("FMSUrl");
				}
			}
		}
		
		private int _trainingSessionId;
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual int TrainingSessionId
		{
			get
			{
				return this._trainingSessionId;
			}
			set
			{
				if(this._trainingSessionId != value)
				{
					this.OnPropertyChanging("TrainingSessionId");
					this._trainingSessionId = value;
					this.OnPropertyChanged("TrainingSessionId");
				}
			}
		}
		
		private string _eventName;
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string EventName
		{
			get
			{
				return this._eventName;
			}
			set
			{
				if(this._eventName != value)
				{
					this.OnPropertyChanging("EventName");
					this._eventName = value;
					this.OnPropertyChanged("EventName");
				}
			}
		}
		
		private TraiiningSessions _traiiningSessions;
		public virtual TraiiningSessions TraiiningSessions
		{
			get
			{
				return this._traiiningSessions;
			}
			set
			{
				if(this._traiiningSessions != value)
				{
					this.OnPropertyChanging("TraiiningSessions");
					this._traiiningSessions = value;
					this.OnPropertyChanged("TraiiningSessions");
				}
			}
		}
		
		#region INotifyPropertyChanging members
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		protected virtual void OnPropertyChanging(string propertyName)
		{
			if(this.PropertyChanging != null)
			{
				this.PropertyChanging(this, new PropertyChangingEventArgs(propertyName));
			}
		}
		
		#endregion
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
		#region ISerializable Implementation
		
		public TrainingSessionLiveEvents()
		{
		}
		
		protected TrainingSessionLiveEvents(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			this.Id = info.GetInt32("Id");
			this.StartDate = (DateTime)info.GetValue("StartDate", typeof(DateTime));
			this.FMSUrl = info.GetString("FMSUrl");
			this.TrainingSessionId = info.GetInt32("TrainingSessionId");
			this.EventName = info.GetString("EventName");
			CustomizeDeserializationProcess(info, context);
		}
		
		public virtual void GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			info.AddValue("Id", this.Id, typeof(int));
			info.AddValue("StartDate", this.StartDate, typeof(DateTime));
			info.AddValue("FMSUrl", this.FMSUrl, typeof(string));
			info.AddValue("TrainingSessionId", this.TrainingSessionId, typeof(int));
			info.AddValue("EventName", this.EventName, typeof(string));
			CustomizeSerializationProcess(info, context);
		}
		
		partial void CustomizeSerializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		partial void CustomizeDeserializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		#endregion
	}
}
#pragma warning restore 1591
